inertials:
  base_link:
    inertia:
      ixx: 0.007626114308954572
      ixy: -2.648795415747583e-08
      ixz: -1.6761394034827453e-11
      iyy: 0.0076284118233769125
      iyz: -6.173603713794146e-07
      izz: 0.012460460395368212
    mass: 3.034850000000001
    origin:
      rpy: 0 0 0
      xyz: 0.10000000035734306 -0.0999788124707297 0.02608263021598558
  frame_left_arm_ee:
    inertia:
      ixx: 1.0e-09
      ixy: 0
      ixz: 0
      iyy: 1.0e-09
      iyz: 0
      izz: 1.0e-09
    mass: 1.0e-09
    origin:
      rpy: 0 0 0
      xyz: 0 0 0
  frame_right_arm_ee:
    inertia:
      ixx: 1.0e-09
      ixy: 0
      ixz: 0
      iyy: 1.0e-09
      iyz: 0
      izz: 1.0e-09
    mass: 1.0e-09
    origin:
      rpy: 0 0 0
      xyz: 0 0 0
  left_arm_l1:
    inertia:
      ixx: 0.0011207403165077376
      ixy: -1.601189280149241e-06
      ixz: -1.5662574368295944e-06
      iyy: 0.0014066300491074755
      iyz: -2.8537212756230654e-05
      izz: 0.0008510086157856846
    mass: 1.0775300000000003
    origin:
      rpy: 0 0 0
      xyz: -1.5765990861716596e-05 -0.0020310989930250115 -0.05298175428059109
  left_arm_l2:
    inertia:
      ixx: 0.0002236341691723969
      ixy: -2.3278535178090075e-07
      ixz: 9.301068398185412e-08
      iyy: 0.00010148027263779045
      iyz: -5.4667081241453686e-05
      izz: 0.0002137229734621309
    mass: 0.25256000000000006
    origin:
      rpy: 0 0 0
      xyz: 4.1374361756272345e-05 0.03272370619566981 0.005508443599477
  left_arm_l3:
    inertia:
      ixx: 0.004100338965753058
      ixy: 1.1939161056224873e-06
      ixz: 7.366817501927928e-05
      iyy: 0.004250389356331734
      iyz: 3.202739203261214e-05
      izz: 0.0005863500767506302
    mass: 0.987950000000001
    origin:
      rpy: 0 0 0
      xyz: -0.0011356182007953432 -0.001835124918895825 0.0907765111069204
  left_arm_l4:
    inertia:
      ixx: 0.000829635597145282
      ixy: -1.8547051757087898e-05
      ixz: 5.447549522839761e-06
      iyy: 0.0004183156586466117
      iyz: 4.5774087658336826e-05
      izz: 0.0006226603869997744
    mass: 0.51661
    origin:
      rpy: 0 0 0
      xyz: 0.0070450096094708805 0.05747426859195603 -0.030023800580192966
  left_arm_l5:
    inertia:
      ixx: 0.0004293600728598691
      ixy: 4.747482679173906e-06
      ixz: -6.358103709120229e-06
      iyy: 0.00033809882760553966
      iyz: 3.829150525279354e-06
      izz: 0.0002642937200265032
    mass: 0.48206999999999967
    origin:
      rpy: 0 0 0
      xyz: -0.0009501771684087459 -0.002718640750254248 -0.0471508462547845
  left_arm_l6:
    inertia:
      ixx: 0.00015685587016764225
      ixy: 4.225040354726119e-06
      ixz: 2.1525402347611654e-07
      iyy: 0.0001599171418373879
      iyz: -5.316452916443136e-06
      izz: 0.0001489639914485405
    mass: 0.35155
    origin:
      rpy: 0 0 0
      xyz: -0.0011119966392037167 -0.0007581455154178877 -0.038050647595123596
  left_arm_l7:
    inertia:
      ixx: 0.0009954248739614056
      ixy: -1.8864543693612335e-06
      ixz: 3.5929655318955823e-07
      iyy: 0.0002788695252316954
      iyz: -0.0001359497861495952
      izz: 0.0009219683276302782
    mass: 0.5217229457824417
    origin:
      rpy: 0 0 0
      xyz: -5.0692877950010084e-05 0.07261078345629761 0.01648535246571335
  right_arm_l1:
    inertia:
      ixx: 0.0011207404080417237
      ixy: -1.60118106963931e-06
      ixz: -1.566189709947461e-06
      iyy: 0.0014066301382452825
      iyz: -2.8537194433717575e-05
      izz: 0.0008510086192510778
    mass: 1.07753
    origin:
      rpy: 0 0 0
      xyz: -1.575610019623804e-05 -0.0020310948193574653 -0.052981765376839074
  right_arm_l2:
    inertia:
      ixx: 0.00010148027130008127
      ixy: -2.3278753841091095e-07
      ixz: 5.466708182351637e-05
      iyy: 0.0002236341657790433
      iyz: -9.301052863232653e-08
      izz: 0.00021372297377495253
    mass: 0.25256000000000006
    origin:
      rpy: 0 0 0
      xyz: 0.0327237060482337 4.137552450527311e-05 -0.00550844530919722
  right_arm_l3:
    inertia:
      ixx: 0.004100338912610468
      ixy: -1.1939230428565069e-06
      ixz: -7.366834991453059e-05
      iyy: 0.00425038934063517
      iyz: 3.2027238309073935e-05
      izz: 0.0005863500567210092
    mass: 0.987950000000001
    origin:
      rpy: 0 0 0
      xyz: -0.0011356223295173554 0.0018351172459148504 -0.09077651068021492
  right_arm_l4:
    inertia:
      ixx: 0.0008296356460395705
      ixy: 1.8547017664576803e-05
      ixz: -5.44754384529401e-06
      iyy: 0.00041831566444395114
      iyz: 4.577411630449051e-05
      izz: 0.000622660438762305
    mass: 0.51661
    origin:
      rpy: 0 0 0
      xyz: 0.0070450065433802665 -0.05747427073527714 0.030023805105189913
  right_arm_l5:
    inertia:
      ixx: 0.00042936009842529254
      ixy: -6.509887476875372e-06
      ixz: 6.490610382947341e-06
      iyy: 0.0003382379976057461
      iyz: 3.829162749367516e-06
      izz: 0.00026443291789511765
    mass: 0.4820699999999997
    origin:
      rpy: 0 0 0
      xyz: 0.0007836652467760791 -0.0027186516842235254 -0.047150840204513475
  right_arm_l6:
    inertia:
      ixx: 0.0001568558703401327
      ixy: -4.225041985908127e-06
      ixz: -2.1525528963189414e-07
      iyy: 0.00015991714407892087
      iyz: -5.316455799796832e-06
      izz: 0.0001489639933958961
    mass: 0.35155
    origin:
      rpy: 0 0 0
      xyz: -0.0011119933762254361 0.0007581440954451527 0.03364448319642487
  right_arm_l7:
    inertia:
      ixx: 0.0012921131898931
      ixy: -1.8786626619267191e-06
      ixz: -9.5733633700521e-06
      iyy: 0.0005715042702320766
      iyz: -0.0001359795459171535
      izz: 0.0009179147163587071
    mass: 0.5217229457824493
    origin:
      rpy: 0 0 0
      xyz: -5.069189381619416e-05 0.07185869176869258 0.01648510692704465
  torso_link:
    inertia:
      ixx: 0.010732924384238396
      ixy: -8.809074230899756e-05
      ixz: 0.000282266895366853
      iyy: 0.08023223423022291
      iyz: 1.8078703618131843e-08
      izz: 0.07290538299045393
    mass: 3.6039500000000007
    origin:
      rpy: 0 0 0
      xyz: -0.3276772887928212 -0.0003140079288505996 -0.036175732482987215
  waist_link:
    inertia:
      ixx: 0.00441118094753532
      ixy: -0.0001239440794254658
      ixz: 2.9347590916725035e-05
      iyy: 0.0032720233468132814
      iyz: 2.3667040069194398e-05
      izz: 0.002747876656843114
    mass: 2.1228924324899205
    origin:
      rpy: 0 0 0
      xyz: 0.0012641480034824633 0.0008562754970587279 0.06385633173770963
